### ISSUE TITLE
Improve documentation for user-defined rules

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#119]
- [ ] Factor out into a separate page
- [ ] Examples
  - [ ] yaml
  - [ ] example of usage
- [ ] Make sure all features are covered

**Comment by 0pdd** [comment]
@deemp the puzzle [#151](https://github.com/objectionary/normalizer/issues/151) is still not solved.

**Comment by 0pdd** [comment]
@deemp the only puzzle [#151](https://github.com/objectionary/normalizer/issues/151) is solved here.
