### ISSUE TITLE
Common.hs:184: normalize the deltas instead of ignoring...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/normalizer#176]
The puzzle `120-5abe27a3` from #120 has to be resolved: 

https://github.com/objectionary/normalizer/blob/6ca51cf591095bebf0741c9e449c2b02f65127c0/eo-phi-normalizer/src/Language/EO/Phi/Rules/Common.hs#L184-L184

The puzzle was created by @aabounegm on 04-Mar-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by aabounegm** [comment]
We no longer have `VTX`, so I think it now makes sense to compare `Bytes` directly. Should I remove this line?
