### ISSUE TITLE
Get details about programs for acceptance testing

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#240]
## Questions

- Stage 2:
  - How many programs will be used for acceptance testing?
  - When will the programs be available?
- Stage 3:
  - How many programs will be used for acceptance testing?
  - When will the programs be available?

## Details
- Stages
  - The stage 1 spans T+0 months - T+6 months.
  - The stage 2 spans T+6 months - T+9 months.
  - The stage 3 spans T+9 months - T+12 months.
  - T is the start of the project on 09.01.2024.
- Programs for acceptance testing
  - For the stage 1, we use programs from the eo repo ([all tests](https://github.com/objectionary/eo/tree/e6358434bb5ae988d508070c9fa06a2a57db5192/eo-runtime/src/test/eo/org/eolang), [selected tests](https://github.com/objectionary/normalizer/blob/4bf6dba3b7c24e50a45daffa4e22f3118e2140c6/pipeline/config.yaml)) as suggested by the customer ([link](https://github.com/objectionary/normalizer/issues/69#issuecomment-1921181575)).
  - For the stage 2, the approximate known number is 20+.
  - For the stage 3, the approximate known number is 50+.

**Comment by yegor256** [comment]
@deemp I suggest to use unit test from the objectionary/eo repository
