### ISSUE TITLE
Use the same BNFC version

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#25]
- [ ] Make the version of BNFC fixed for devs so that changes to grammar don't produce larger than necessary diffs (like [this one](https://github.com/objectionary/normalizer/pull/22/commits/0ddcdd98fb262900f042d2c274144a678470bde1)).

`BNFC 2.9.6` doesn't exist on [Hackage](https://hackage.haskell.org/package/BNFC). The latest version is `2.9.5`. 

It also doesn't exist in our current resolver.

https://github.com/objectionary/normalizer/blob/c1b2a139e981f589b69f7e98b32c58db9c731f72/stack.yaml#L1

https://www.stackage.org/nightly-2023-12-14

However, I see comments that some files were generated by bnfc 2.9.6.

https://github.com/objectionary/normalizer/blob/c1b2a139e981f589b69f7e98b32c58db9c731f72/eo-phi-normalizer/src/Language/EO/Phi/Syntax/Abs.hs#L1

https://github.com/objectionary/normalizer/blob/c1b2a139e981f589b69f7e98b32c58db9c731f72/eo-phi-normalizer/src/Language/EO/Phi/Syntax/Print.hs#L1

**Comment by aabounegm** [comment]
That was my bad. I had BNFC built from source (`master` branch, which has the unreleased `v2.9.6`) from when I was contributing a PR. I have now removed my local build and installed `v2.9.5` using Stack.
I see that the generated files now use `v2.9.5` since #22, so I think we can close this issue.

**Comment by deemp** [comment]
Can we make use of full positions version? Related to https://github.com/objectionary/normalizer/issues/19.

If yes, pls, add your version to [extra-deps](https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps) in `stack.yaml`.

**Comment by aabounegm** [comment]
Do we really need it (at least right now)?
Even if so, I think #19 is enough and no need to keep this unrelated issue open.

**Comment by fizruk** [comment]
Can we close this issue?
