### ISSUE TITLE
Get approval of metrics from Yegor

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#252]
@yegor256, we have documented the metrics on our site
- [code](https://github.com/objectionary/normalizer/blob/9c1ea575abf3041859f44c2aa454408b9c7c593a/site/docs/src/commands/normalizer-metrics.md)
- [rendered](https://www.objectionary.com/normalizer/docs/commands/normalizer-metrics.html)

Do you approve of them?

**Comment by yegor256** [comment]
@deemp yes, they look correct
