### ISSUE TITLE
Support LaTeX output

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#255]
Add the `--latex` option for the `dataize` command.

## Format

- Should we support a single format?
- Should we support the format used in the [phi-paper](https://github.com/yegor256/phi-paper/blob/750173428be0eedd5989ac3f153823737302fd60/sections/calculus.tex#L855-L865)?
  - Yes. this format is supported by the [eolang](https://ctan.org/pkg/eolang) LaTeX package ([link](https://github.com/objectionary/normalizer/issues/255#issuecomment-2073908758))

  ![image](https://github.com/objectionary/normalizer/assets/48378098/1697b266-453b-4443-8c3f-c7e711e7af14)

## Example

Input program ([nop.phi](https://github.com/objectionary/normalizer/blob/a080ef0a49a91f93d3c901167387223f1322758c/eo-phi-normalizer/data/0.36.0/org/eolang/nop.phi)):

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        nop ↦ ⟦
          args ↦ ∅,
          φ ↦ Φ.org.eolang.bool(
            α0 ↦ Φ.org.eolang.bytes(
              Δ ⤍ 01-
            )
          )
        ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

Output:

```
???
```

**Comment by yegor256** [comment]
@deemp the format that is used in the paper is the one supported by the [eolang](https://ctan.org/pkg/eolang) LaTeX package. It is more compact than a plain math-mode LaTeX. Let's try to use it.

**Comment by deemp** [comment]
@yegor256, is it enough to support just that one format for now?

**Comment by deemp** [comment]
@yegor256, how should the example program look like in that format?

**Comment by yegor256** [comment]
@deemp check [this file](https://mirrors.mit.edu/CTAN/macros/latex/contrib/eolang/eolang.pdf), it explains all the syntax of the `eolang` LaTeX package:

<img width="954" alt="Screenshot 2024-04-24 at 10 23 02" src="https://github.com/objectionary/normalizer/assets/526301/e89e84f6-6048-431b-85bf-1ea4ad644880">

**Comment by yegor256** [comment]
@deemp for simplicity, use `QQ` instead of `Q.org.eolang`

**Comment by yegor256** [comment]
@deemp this is how the output should look (using your example above):

```
\begin{phiquation}
{
  [[
    org -> [[
      eolang -> [[
        nop -> [[
          args -> ?,
          @ -> QQ.bool(
            0-> QQ.bytes(
              D> 01-
            )
          )
        ]],
        L> Package
      ]],
      L> Package
    ]]
  ]]
}
\end{phiquation}
```

**Comment by yegor256** [comment]
@deemp you take an expression as an input and produce a new expression as an output. We need LaTeX log of each steps you took. Thus, the full document is not needed from you (with the `\begin{}`). Just print the expressions, one normalization step per line.

**Comment by eyihluyc** [comment]
@yegor256,

For such program

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        nop ↦ ⟦
          args ↦ ∅,
          φ ↦ Φ.org.eolang.bool(
            α0 ↦ Φ.org.eolang.bytes(
              Δ ⤍ 01-
            )
          )
        ⟧,
        x ↦ ⟦ z ↦ ⟦⟧ ⟧.z,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

we get the following output after `dataize --chain` command:

```
[[ org -> [[ eolang -> [[ nop -> [[ args -> ?, @ -> QQ.bool( \alpha_0 -> QQ.bytes( D> 01- ) ) ]], x -> [[ z -> [[  ]] ]].z, L> Package ]], L> Package ]] ]]
[[ org -> [[ eolang -> [[ nop -> [[ args -> ?, @ -> QQ.bool( \alpha_0 -> QQ.bytes( D> 01- ) ) ]], x -> [[  ]]( ^ -> [[  ]] ), L> Package ]], L> Package ]] ]]
[[ org -> [[ eolang -> [[ nop -> [[ args -> ?, @ -> QQ.bool( \alpha_0 -> QQ.bytes( D> 01- ) ) ]], x -> [[ ^ -> [[  ]] ]], L> Package ]], L> Package ]] ]]
```

please let us know if this meets your expectations or if you have any suggestions for improvements.

**Comment by eyihluyc** [comment]
> @deemp check [this file](https://mirrors.mit.edu/CTAN/macros/latex/contrib/eolang/eolang.pdf), it explains all the syntax of the `eolang` LaTeX package:
> 
> <img alt="Screenshot 2024-04-24 at 10 23 02" width="954" src="https://private-user-images.githubusercontent.com/526301/325120191-e89e84f6-6048-431b-85bf-1ea4ad644880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDU2MjEsIm5iZiI6MTcxNDA0NTMyMSwicGF0aCI6Ii81MjYzMDEvMzI1MTIwMTkxLWU4OWU4NGY2LTYwNDgtNDMxYi04NWJmLTFlYTRhZDY0NDg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMTQyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzMwZDQwNTgzMmU2NGNjNDc2MDUzMTM3YWY0OGNiNTg3NTdmZTA2OTAzYWZlZWVkYzAwNGMxMGNjNmIzZGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gptt2EodXJeJgIMdPWFykkqTaZtlnUQ5WFlI4fmpVa0">

@yegor256 This does not mention `⊥`; could you please clarify how `⊥` should be handled?

**Comment by yegor256** [comment]
@eyihluyc it's `\dead`

**Comment by yegor256** [comment]
@deemp looks perfect
