### ISSUE TITLE
Document changes in atoms between different versions of EO

### ISSUE THREAD

**Issue by aabounegm** [objectionary/normalizer#344]
Under [`eo-phi-normalizer/data`](https://github.com/objectionary/normalizer/tree/master/eo-phi-normalizer/data), we have a collection of $\varphi$ programs for testing, versioned by the EO version with which they're compatible. Some of these programs contain $\lambda$-assets, but the "signature" of these atoms can change from one version to another (e.g.: changing param name/count). A `CHANGELOG.md` should be added to that directory, documenting what atoms changed from one version to the next to make it easier to identify compatibility with unit tests.
It would also be great if a `README.md` can be added, describing what each atom (latest version) does, perhaps with links to their original implementation in Java.

Useful links:
- [On the Origin of Objects (paper)](https://arxiv.org/abs/2206.02585)
- [Java implementation of atoms](https://github.com/objectionary/eo/tree/master/eo-runtime/src/main/java/EOorg/EOeolang)

**Comment by deemp** [comment]
Closing as not planned
