### ISSUE TITLE
Update custom rules to latest version of the paper

### ISSUE THREAD

**Issue by aabounegm** [objectionary/normalizer#345]
Reduction rules in the [phi paper](https://github.com/yegor256/phi-paper/) (page 12) have been updated recently with more descriptive names rather than numbers. Also, the rules themselves have changed, some rules may have been added, and others may have been removed. [`yegor.yaml`](https://github.com/objectionary/normalizer/blob/master/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml) should be reconciled with these changes.

**Comment by RoukayaZaki** [comment]
the paper link is private or isn't available anymore

**Comment by RoukayaZaki** [comment]
The phi paper is not available @aabounegm

**Comment by fizruk** [comment]
Superseded by #436.
