### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#36]
## Subtasks

- [ ] Add tests to [yegor.yaml](https://github.com/objectionary/normalizer/blob/17dc8cbbba28b045f0c4640080df2251e6717861/eo-phi-normalizer/test/eo/phi/rules/yegor.yaml) so that each rule has at least 3 unit tests

**Comment by fizruk** [comment]
We already have `dataization.yaml` and `confluence.yaml` tests in addition to some tests for each rule. Do we need more unit tests? I think it is enough to have 2-3 tests per each rule in `yegor.yaml`, for example, not 5.

**Comment by deemp** [comment]
@fizruk, as I understand, they're not unit tests for specific rules
