### ISSUE TITLE
Which tests should we use?

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#360]
@yegor256 

- Which tests should we use?
- If we should use all available tests, how to measure metrics for programs with one formation?

For some eo-runtime tests ([link](https://github.com/objectionary/eo/blob/master/eo-runtime/src/test/eo/org/eolang)), we have one formation at the `org.eolang` path in the non-normalized and normalized version. So, the normalizer can't reduce the number of formations. Example:

non-normalized:

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        compares-two-bools ↦ ⟦
          φ ↦ Φ.org.eolang.true.eq(
            α0 ↦ Φ.org.eolang.true
          )
        ⟧,
        ...
     ⟧
  ⟧
}
```

normalized:

```
{
  ⟦ 
    org ↦ ⟦ 
       eolang ↦ ⟦ 
         compares-two-bools ↦ ⟦ 
           Δ ⤍ 01- 
         ⟧
       ⟧
    ⟧
  ⟧
}
```

**Comment by yegor256** [comment]
@deemp I believe, you should use all tests available in the EO project. Yes, sometimes you can't reduce the number of formations.

**Comment by deemp** [comment]
Should we print `N/A` in such cases?

![image](https://github.com/objectionary/normalizer/assets/48378098/a77a680d-e3b7-4981-b209-4a7e72feeced)
