### ISSUE TITLE
Fix the Celsius example

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#374]
The `celsius.phi` ([link](https://github.com/objectionary/normalizer/blob/42fa5463e9f0af9580de3ce001f33aa4491d5df9/site/docs/src/common/celsius.md)) is currently not a package. Hence, dataization produces not just bytes, as before https://github.com/objectionary/normalizer/commit/f973c5101ff7597390e7a93236d649f7104baa5d.

```
normalizer dataize --recursive --rules eo-phi-normalizer/test/eo/phi/rules/yegor.yaml celsius.phi 
```

```
Φ.org.eolang.float (as-bytes ↦ Φ.org.eolang.bytes (Δ ⤍ 01-01-00-00-00-00-00-00-00-07-00-00-00-00-00-00-19-FF-FF-FF-FF-FF-FF-FF-D0)).times (x ↦ ⟦ Δ ⤍ 01-01-00-00-00-00-00-00-00-07-CD-CC-CC-CC-CC-CC-1C-FF-FF-FF-FF-FF-FF-FF-CC ⟧).plus (x ↦ ⟦ Δ ⤍ 01-01-00-00-00-00-00-00-00-07-00-00-00-00-00-00-10-FF-FF-FF-FF-FF-FF-FF-D1 ⟧)
```

**Comment by fizruk** [comment]
Fixed in 2c85def8639d9d47d4b1accaeb113e188d6eeb26.
