### ISSUE TITLE
Wrap data into bytes after dataization

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#394]
@yegor256, @maxonfjvipon

Tests work if we wrap data into `Φ.org.eolang.bytes` (see https://github.com/objectionary/eo/issues/3213#issuecomment-2149833641).

**Comment by maxonfjvipon** [comment]
@deemp I believe yes, you should do it on your side. EO has more restrictions than PHI (not every PHI expression can be converted to valid EO). Since `UnphiMojo` is part of EO ecosystem the only thing it can do is expect PHI expression is to be "valid" and convertable to EO

**Comment by deemp** [comment]
https://github.com/objectionary/eo/issues/3213#issuecomment-2150032168
