### ISSUE TITLE
Fix changes in markdown files aren't committed

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#469]
## Details

Currently, `files` aren't split, so no changes are discovered.

https://github.com/objectionary/normalizer/blob/34833ecaac2d2608493140bb936c28837465e64a/.github/workflows/ghc.yml#L259

https://github.com/objectionary/normalizer/blob/34833ecaac2d2608493140bb936c28837465e64a/scripts/lib.sh#L151

## Subtasks

- [x] Use an array and expand it in the script

**Comment by 0crat** [comment]
@deemp Thanks for submitting this ticket! Unfortunately, it wasn't accepted by the team. As per our policy, there's a **-16** point penalty for rejected issues. Your current balance is [+177](https://www.eolang.org/zerocracy/objectionary-vitals.html). Don't be discouraged! Your contributions are valuable for improving our project quality. Keep [reporting](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs and suggesting enhancements, but try to be more thorough next time. Remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) when properly reported!

**Comment by yegor256** [comment]
@deemp "not accepted by the team" means that neither "bug" nor "enhancement" labels were attached.
