### ISSUE TITLE
Add a step for building the normalizer to the Maven plugin

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#476]
## Details

- @yegor256 wrote a Maven Plugin for the whole pipeline
- The pipeline is in a Dockerfile
- `normalizer` should be built in that pipeline

## Subtasks

- [x] get a link to the Dockerfile from @yegor256
- [ ] add steps to build `normalizer` to the Dockerfile

**Comment by yegor256** [comment]
@deemp here it is: https://github.com/objectionary/hone-maven-plugin/issues/19

**Comment by deemp** [comment]
I believe this issue is superseded by https://github.com/objectionary/hone-maven-plugin/issues/19

**Comment by yegor256** [comment]
@deemp we can close this ticket, I believe
