### ISSUE TITLE
Collect EO programs

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#69]
Superseded by #93 

- [ ] - [ ] Collect 10 EO programs whose dataization produces some text output
  1. Hello, world
     ```
     [args] > app
       QQ.io.stdout > @
         "Hello, world!\n"
     ```
  1. Prim's algorithm [link](https://github.com/objectionary/eo-graphs/blob/master/src/eo/prim.eo)

**Comment by yegor256** [comment]
@deemp take tests from this directory: https://github.com/objectionary/eo/tree/master/eo-runtime/src/test/eo/org/eolang 

Let's say, this is the test:

```
# Test.
[] > writes-into-cage
  # Object with free attribute.
  [z] > a
  cage a > x
  eq. > @
    seq
      *
        x.write
          a 7
        x.z
    7
```

Modify it like this, and it will become an app that prints "Works!" when if finishes:

```
# Test.
[] > app
  # Object with free attribute.
  [z] > a
  cage a > x
  seq > @
    *
      eq.
        seq
          *
            x.write
              a 7
            x.z
        7
      QQ.io.stdout "Works!"
```
