### ISSUE TITLE
Set up a site

### ISSUE THREAD

**Issue by deemp** [objectionary/normalizer#74]
README is a bit too big.

Use
- [x] mdBook
- [ ] or, MkDocs

Add:
-  [x] link to package docs

**Comment by aabounegm** [comment]
What about the Wiki in GitHub?

**Comment by deemp** [comment]
- How to migrate a wiki when we (hypothetically) later switch to GitLab?
- How to get offline docs?

**Comment by fizruk** [comment]
Let's use mdBook, @deemp please set up this.
