### ISSUE TITLE
Check that after applying a rule no metavariables are left

### ISSUE THREAD

**Issue by fizruk** [objectionary/normalizer#82]
See `convertRule`:

https://github.com/objectionary/normalizer/blob/be6157873e6c7745b86726a567f204cb216a2300/eo-phi-normalizer/src/Language/EO/Phi/Rules/Yaml.hs#L72-L79

**Comment by 0pdd** [comment]
@fizruk the puzzle [#86](https://github.com/objectionary/normalizer/issues/86) is still not solved.

**Comment by 0pdd** [comment]
@fizruk the only puzzle [#86](https://github.com/objectionary/normalizer/issues/86) is solved here.
