### ISSUE TITLE
Yaml.hs:78: check that obj' does not have any metavariables

### ISSUE THREAD

**Issue by 0pdd** [objectionary/normalizer#86]
The puzzle `82-b088af7b` from #82 has to be resolved: 

https://github.com/objectionary/normalizer/blob/2f22e413010730c6eeff1d70752b8884d6620b9e/eo-phi-normalizer/src/Language/EO/Phi/Rules/Yaml.hs#L78-L78

The puzzle was created by @fizruk on 02-Feb-24. 

Estimate: 20 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fizruk** [comment]
Closed by #88.
